version: '3.1'
networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #mysql root账号密码
      MYSQL_USER: "www" #mysql普通用户账号
      MYSQL_PASSWORD: "www123" #mysql 普通账号密码
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d #mysql配置文件目录
      - ./mysql/data:/var/lib/mysql #mysql数据存放目录
      - ./mysql/log:/var/log/mysqld # mysql错误日志
    networks:
      internal_net:
        ipv4_address: 172.16.0.10
    ports:
      - 3306:3306
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456    
    # volumes:
      # - $PWD/mongo:/etc/mongo
      # - $PWD/mongo/data:/data/dbh
    networks:
      internal_net:
        ipv4_address: 172.16.0.20
    ports:
      - 27017:27017
  mongo-express: #mongodb图形管理界面
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      internal_net:
        ipv4_address: 172.16.0.30
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/
  redis:
    image: redis:7.2.2
    container_name: redis
    restart: always
    privileged: true
    networks:
      internal_net:
        ipv4_address: 172.16.0.40
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes: 
      - ./redis/logs:/redis/logs    #日志文件地址是在配置文件中配置的[logfile项]，宿主容器映射日志文件目录要与配置文件中的日志目录一致
      - ./redis/data:/data  # 持久化数据
      - ./redis/conf:/redis/conf # 在宿主机./redis/conf/下放redis.conf配置文件，注意需要将 daemonized 配置项注释掉（该配置项控制是否后台运行），否则容器运行后貌似无法探活，docker认为服务未启动会一直重启
    command: redis-server  /redis/conf/redis.conf # 启动redis-server 配置文件路径要以容器中的路径为准
    
    
  redis2:
    image: redis:7.2.2
    container_name: redis2
    restart: always
    privileged: true
    networks:
      internal_net:
        ipv4_address: 172.16.0.50
    ports:
      - 6380:6379
    environment:
      TZ: Asia/Shanghai
    volumes: 
      - ./redis2/logs:/redis/logs    #日志文件地址是在配置文件中配置的[logfile项]，宿主容器映射日志文件目录要与配置文件中的日志目录一致
      - ./redis2/data:/data  # 持久化数据
      - ./redis2/conf:/redis/conf # 在宿主机./redis/conf/下放redis.conf配置文件，注意需要将 daemonized 配置项注释掉（该配置项控制是否后台运行），否则容器运行后貌似无法探活，docker认为服务未启动会一直重启
    command: redis-server  /redis/conf/redis.conf --slaveof 172.16.0.40 6379 # 启动redis-server 配置文件路径要以容器中的路径为准

